### ISSUE TITLE
Call to a member function editUrl() on null after migrating

### ISSUE THREAD

**Issue by matrad** [statamic/cms#1636]
After Migrating v2 to v3 I get on some collection Instances on the index page - for example on `http://rentmas.test/cp/globals` the Error Message `Call to a member function editUrl() on null`

If you like to reproduce the error I also can send you (privately) my statamic page.

![Bildschirmfoto 2020-03-22 um 11 39 05](https://user-images.githubusercontent.com/660903/77247461-c2770a00-6c31-11ea-91a3-f59485d72e80.png)

**Comment by jackmcdade** [comment]
I do think this one was fixed already - have you tried updating to the latest (beta-23)?

**Comment by jackmcdade** [comment]
Hey there, we haven't heard back on this (and am pretty sure it's fixed) so I'm going to need to close the issue to help us stay organized. You can always reply with more info so we can reopen it or feel free start a fresh one anytime. Either is fine by us!

**Comment by conradfuhrman** [comment]
Worth reopening, I just ran into this issue when dealing with Multisite. If the Global isn't assigned to the site you're currently editing and you click on Globals it will throw this error. On Beta 27 currently.

**Comment by martink635** [comment]
This issue is still present, if 1 global set is not assigned you get a 500 error

**Comment by rrelmy** [comment]
This is a very irritating issue and breaks the use of the site switcher inside the cp

*Steps to reproduce*
1. Create a global in the cp
2. Switch the site in the header
3. Go to the globals overview

```
Error
Call to a member function editUrl() on null
http://xyz.localhost/cp/globals?site=en

vendor/statamic/cms/src/Http/Controllers/CP/Globals/GlobalsController.php:31
```

---

I think there more issues with the site switcher and globals.

Switching the site inside a global that is available in that site shows another error
```
Call to a member function title() on null (View: .../vendor/statamic/cms/resources/views/layout.blade.php)
```

**Comment by rrelmy** [comment]
Not yet a 100% sure but I think the update 3.1.28 or 3.1.29 has fixed the issue
