### ISSUE TITLE
[beta 34+ and 3.0.x] Cannot keep Markdown.php file in two different lang folders as it creates garbage in Fieldtypes view

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#2031]
## Bug Description
I got some garbage related to Markdown when adding a first field to a new fieldset

## How to Reproduce
1. in ```my_base_site_folder/resources/lang/fr/``` add a file called markdown.php
2. Create a brand new Fieldset, then click on Create a field OR try to add any field to a blueprint

There isn't any problem when this markdown file is ONLY located in ```my_base_site_folder/vendor/statamic/cms/resources/lang/fr```

## Extra Detail

![Capture d'écran 2020-07-06 18 06 34](https://user-images.githubusercontent.com/1823359/86614776-cac23d80-bfb3-11ea-8675-25f2bfad1750.png)

![Capture d'écran 2020-07-06 18 20 41](https://user-images.githubusercontent.com/1823359/86616524-3dccb380-bfb6-11ea-815c-b30e18662f26.png)

## Environment

**Statamic version:** 3.0.0.-beta-{34}

**PHP version:** 7.{4.2}

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by ebeauchamps** [comment]
Now solved

**Comment by ebeauchamps** [comment]
Sorry...It is apparently solved in 3.0.7 but when I update "my" French localisation files for the CP, I get this error back. So I have to reopen it.

**Comment by ebeauchamps** [comment]
OK, found the issue: see "How to reproduce" above

**Comment by damcclean** [comment]
@ebeauchamps I've swapped my fresh Statamic install's locale in `config/app.php` to `fr` and created the file ( `resources/lang/fr/markdown.php`) but I'm unable to replicate the issue. 

Should I be doing something else in order to replicate this?

**Comment by ebeauchamps** [comment]
Probably: you should display the CP in French I guess (in your user.yaml file, put 
```
preferences:
  locale: fr
```

**Comment by damcclean** [comment]
Thanks for your response! Although, I still can't seem to reproduce it... the text `Markdown` displays, which I think should be the case until something overrides it (correct me if I'm wrong).

![image](https://user-images.githubusercontent.com/19637309/93142212-7affa100-f6dd-11ea-8226-39272d95c280.png)
![image](https://user-images.githubusercontent.com/19637309/93142267-979bd900-f6dd-11ea-819e-5cea16071b96.png)

Would you mind creating up a fresh Statamic site to reproduce the issue yourself and let me know if you still encounter the issue.

**Comment by ebeauchamps** [comment]
Sure! but later on, it's midnight here!! I'll let you know.

**Comment by ebeauchamps** [comment]
## How to Reproduce
1. in ```my_base_site_folder/resources/lang/fr/``` add the markdown.php file already located in ```my_base_site_folder/vendor/statamic/cms/resources/lang/fr```
2. Create a brand new Fieldset, then click on Create a field OR try to add any field to a blueprint

There isn't any problem when this markdown.php file is ONLY located in ```my_base_site_folder/vendor/statamic/cms/resources/lang/fr```

![Capture d’écran 2020-09-15 à 22 13 42](https://user-images.githubusercontent.com/1823359/93260040-160d7f00-f7a1-11ea-9eee-0b254a3687ba.png)
![Capture d’écran 2020-09-15 à 22 14 03](https://user-images.githubusercontent.com/1823359/93260052-19a10600-f7a1-11ea-97f2-760843e80636.png)

## My personal analysis
When working on my translation updates, I put the working copy of my files in ```my_base_site_folder/resources/lang/```
That includes my fr.json file and my fr folder

I am doing this in order to check for my translations as it **should** override the French files located in ```my_base_site_folder/vendor/statamic/cms/resources/lang/```

Actually, I recently discovered that:
1. the fr.json file is overrided
2. the messages.php file is not overrided
3. the markdown.php file (always fully identical between the 2 folders) is creating the above described garbage

### My questions
1. Is there any reason for keeping this particular folder ``my_base_site_folder/resources/lang/``` in Statamic?
2. What is it for?
3. Why cannot we use it to override translations located in ```my_base_site_folder/vendor/statamic/cms/resources/lang/``` ?
4. As the above described behaviour is somewhat recent (beta34), what could be done?

**Comment by jasonvarga** [comment]
The "json" translations are considered global. You can't override them in a vendor directory.
So you need to put it in `resources/lang/fr.json`. It's just the way Laravel works.

The other php based translation files _are_ specific to the vendor (Statamic), so you need to put them in `resources/lang/vendor/statamic/fr/markdown.php`.

However, if you're just trying to test out some translations that you plan to PR into Statamic, you could consider editing them in `vendor/statamic/cms/resources/lang`.
