### ISSUE TITLE
Creating new user from cp with users in database says missing table

### ISSUE THREAD

**Issue by twd3** [statamic/cms#2392]
With users in a database using the default migrations a table called password_activations doesn't get made. If you go to create a new user via the CP you get the error below. I could just make this table but I don't know what is supposed to be in there.

## Extra Detail
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'forge_local.password_activations' doesn't exist (SQL: delete from `password_activations` where `email` = tom@blah.com)C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Database\Connection.php#671Illuminate\Database\QueryException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'forge_local.password_activations' doesn't existC:\_statamic\ma\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php#72Doctrine\DBAL\Driver\PDOException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'forge_local.password_activations' doesn't existC:\_statamic\ma\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php#67

## Environment
Statamic 3.0.7 Pro
Laravel 7.26.1
PHP 7.4.6
aryehraber/statamic-captcha 1.0.3
edalzell/anvil 1.0.4
optimoapps/statamic-bard-text-align 1.0.0
silentz/charge 4.0.2
spatie/statamic-responsive-images 1.2.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by twd3** [comment]
I can figure this out later no biggie.

**Comment by AntiCZ** [comment]
But this is a bug. Why are you closing it?

**Comment by jasonvarga** [comment]
Please try again after upgrading Statamic. I believe this was fixed in 3.0.9.

**Comment by jbardnz** [comment]
I'm getting this exact issue on my site, I installed 3.0.15 and have updated to 3.0.16.

**Comment by edalzell** [comment]
Confirmed, I get this in 3.0.23.

**Comment by mrpatricko** [comment]
Still getting this error in Statamic v3.1.29

Just wondering what the best method is to make these errors go away, as opposed to ignoring them.
