### ISSUE TITLE
Forms File Upload: "An asset container has not been configured" since 3.3.7

### ISSUE THREAD

**Issue by heidkaemper** [statamic/cms#5933]
### Bug description

We have a Statamic form with a file upload. When submitting the form in the frontend, we get the following error:
**"An asset container has not been configured"**

However, the container is correctly defined in the blueprint.

Until Statamic 3.3.6 this worked as expected, since 3.3.7 not anymore.

---

Form Blueprint:
```
...
fields:
  -
    handle: attachments
    field:
      max_files: 1
      type: assets
      container: application_uploads
```

Form Config:
```
title: Test
email:
  -
    to: xyz@xyz.xy
    subject: 'New Submission'
    attachments: true
    html: mails/application
```

Antlers View:
```
{{ form:application files="true" redirect="#form" error_redirect="#form" }}
  ...
  {{ fields }}
    <label>{{ display }}</label>
    <div>{{ field }}</div>
  {{ /fields }}
  ...
{{ /form:application }}
```

Laravel Filesystem Config:
```
'application-uploads' => [
  'driver' => 'local',
  'root' => storage_path('app/application-uploads'),
  'visibility' => 'private',
],
```

It doesn't seem to make a difference whether the old or the new Antlers engine is used.

### How to reproduce

- Create a new form in CP
- Add a asset field and choose a container
- Try to submit the form in frontend with a file

### Logs

```shell
[2022-04-28 09:36:03] local.ERROR: An asset container has not been configured {"exception":"[object] (Statamic\\Fieldtypes\\Assets\\UndefinedContainerException(code: 0): An asset container has not been configured at /web/vendor/statamic/cms/src/Forms/Uploaders/AssetsUploader.php:109)
[stacktrace]
#0 /web/vendor/statamic/cms/src/Forms/Uploaders/AssetsUploader.php(82): Statamic\\Forms\\Uploaders\\AssetsUploader->assetContainer()
#1 /web/vendor/statamic/cms/src/Forms/Uploaders/AssetsUploader.php(46): Statamic\\Forms\\Uploaders\\AssetsUploader->createAsset(Object(Illuminate\\Http\\UploadedFile))
#2 [internal function]: Statamic\\Forms\\Uploaders\\AssetsUploader->Statamic\\Forms\\Uploaders\\{closure}(Object(Illuminate\\Http\\UploadedFile), 0)
#3 /web/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(725): array_map(Object(Closure), Array, Array)
#4 /web/vendor/statamic/cms/src/Forms/Uploaders/AssetsUploader.php(47): Illuminate\\Support\\Collection->map(Object(Closure))
#5 /web/vendor/statamic/cms/src/Forms/Submission.php(115): Statamic\\Forms\\Uploaders\\AssetsUploader->upload(Object(Illuminate\\Http\\UploadedFile))
#6 [internal function]: Statamic\\Forms\\Submission->Statamic\\Forms\\{closure}(Array, 'attachments')
#7 /web/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(725): array_map(Object(Closure), Array, Array)
#8 /web/vendor/statamic/cms/src/Forms/Submission.php(116): Illuminate\\Support\\Collection->map(Object(Closure))
#9 /web/vendor/statamic/cms/src/Http/Controllers/FormController.php(52): Statamic\\Forms\\Submission->uploadFiles(Array)
#10 /web/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\FormController->submit(Object(Illuminate\\Http\\Request), Object(Statamic\\Forms\\Form))
#11 /web/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('submit', Array)
#12 /web/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\FormController), 'submit')
#13 /web/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#14 /web/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#15 /web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /web/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /web/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /web/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /web/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#24 /web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /web/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /web/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /web/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#31 /web/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#32 /web/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#33 /web/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#34 /web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#35 /web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#36 /web/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /web/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /web/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /web/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /web/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#56 /web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#57 /web/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#58 {main}
"}
```

### Versions

Statamic 3.3.9 Pro
Laravel 9.10.0
PHP 8.1.4
aerni/social-links 2.3.0
arckinteractive/statamic-bard-font-size 1.0.0
doublethreedigital/duplicator 2.2.0
jacksleight/statamic-bard-mutator 1.0.4
jacksleight/statamic-bard-texstyle 1.0.1
raynl/generate-slug 1.1.1
rias/statamic-redirect 2.1.2
spatie/statamic-responsive-images 2.11.2
xndbogdan/statamic-bard-text-color 2.2

### Installation

Existing Laravel app

**Comment by staudenmeir** [comment]
It looks like the issue is from coming from this commit: https://github.com/statamic/cms/pull/5789/commits/c904cff561bcd11425a0d97cbd8f572e0c0bdecd

The error only occurs if you multiple asset containers, maybe that's why the tests didn't catch it.

**Comment by LucWollants** [comment]
I experienced the same issue after creating a new container. The container is usable inside the control panel and excepts files to be uploaded, but when used inside a from the error **"An asset container has not been configured"** pops up.

**Comment by marcorieser** [comment]
It seems that the config is only the field handle now.
https://github.com/statamic/cms/blob/4c069210ec725bc6c2667583a0d050ddbc319c9a/src/Forms/Uploaders/AssetsUploader.php#L97

**Comment by dima2306** [comment]
Same as the above two comments.

Also downgraded to 3.3.6 and the issue is fixed.

**Comment by davidatkinswwt** [comment]
I can confirm this is still happening on 3.3.11

**Comment by Aquive** [comment]
I think I encounter the same issue. I am on 3.4.7, is that possible?

When I add an asset to an existing blueprint I get error `An asset container has not been configured` when opening a collection for editing. When I instead add another type, like text. It works without problems.

Is this possibly an issue in my used version (3.4.7)?

**Comment by jasonvarga** [comment]
This issue was about the error happening on front-end forms specifically. You can still get that error in the CP. It's because you haven't selected the container for that field.

**Comment by stjohn-clarity** [comment]
This is now an issue when upgrading from 5.6 to 5.7 and had to downgrade. Very frustrating Statamic.

**Comment by duncanmcclean** [comment]
> This is now an issue when upgrading from 5.6 to 5.7 and had to downgrade. Very frustrating Statamic.

Should be fixed in the next release, see #10272. Until it's fixed, you can downgrade to 5.6.0.
